```dart
const Map<String, String> enStrings = {
  'restaurant_code': 'Restaurant Code',
  'enter_restaurant_code': 'Enter restaurant code',
  'continue': 'Continue',
  'staff_login': 'Staff Login',
  'email': 'Email',
  'password': 'Password',
  'login': 'Login',
  'tables': 'Tables',
  'cart': 'Cart',
  'add': 'Add',
  'submit_order': 'Submit Order',
  'total': 'Total',
  'admin_dashboard': 'Admin Dashboard',
  'create_staff': 'Create Staff',
  'daily_sales_report': 'Daily Sales Report',
  'billing': 'Billing',
  'payment': 'Payment',
  'subtotal': 'Subtotal',
  'discount': 'Discount',
  'tax': 'Tax',
  'grand_total': 'Grand Total',
  'kitchen_orders': 'Kitchen Orders',
  'ready': 'Ready',
  'preparing': 'Preparing',
  'new': 'New',
  'myanmar': 'Myanmar',
  'english': 'English',
  'logout': 'Logout',
  'language': 'Language',
};
```
