```dart
const Map<String, String> mmStrings = {
  'restaurant_code': 'ဆိုင်ကုဒ်',
  'enter_restaurant_code': 'ဆိုင်ကုဒ်ထည့်ပါ',
  'continue': 'ဆက်လုပ်မည်',
  'staff_login': 'ဝန်ထမ်းလော့အင်',
  'email': 'အီးမေးလ်',
  'password': 'စကားဝှက်',
  'login': 'လော့အင်ဝင်မည်',
  'tables': 'စားပွဲများ',
  'cart': 'အော်ဒါတောင်း',
  'add': 'ထည့်မည်',
  'submit_order': 'အော်ဒါတင်မည်',
  'total': 'စုစုပေါင်း',
  'admin_dashboard': 'အက်မင်ဒက်ရှ်ဘုတ်',
  'create_staff': 'ဝန်ထမ်းဖန်တီးရန်',
  'daily_sales_report': 'ယနေ့ရောင်းအားစာရင်း',
  'billing': 'ငွေရှင်းခြင်း',
  'payment': 'ငွေပေးချေမှု',
  'subtotal': 'မူရင်းစုစုပေါင်း',
  'discount': 'လျှော့စျေး',
  'tax': 'အခွန်',
  'grand_total': 'နောက်ဆုံးကျသင့်ငွေ',
  'kitchen_orders': 'မီးဖိုချောင်အော်ဒါများ',
  'ready': 'အဆင်သင့်',
  'preparing': 'ပြင်ဆင်နေသည်',
  'new': 'အသစ်',
  'myanmar': 'မြန်မာ',
  'english': 'အင်္ဂလိပ်',
  'logout': 'ထွက်မည်',
  'language': 'ဘာသာစကား',
};
```
